# Generated by Django 3.0.7 on 2020-07-02 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0004_auto_20200702_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='Ticket.Ticket'),
        ),
    ]
