# Generated by Django 3.0.7 on 2020-07-05 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0007_auto_20200705_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='subject',
            field=models.TextField(default='test', max_length=50),
            preserve_default=False,
        ),
    ]
